#### today we will study pandas

In [9]:
import pandas as pd
s1 = pd.Series([10,20,30,40,50,60,70,80,90,100])
el1 = s1[0]
print(el1)

10

In [14]:
s1

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [15]:
s1.iloc[0:6]

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [16]:
s1.loc[0:6]

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [19]:
data = {
    "name" : ["Abdulrehman", "Anup", "Kaushik", "Shivam", "Vinay", "Ganesh"],
    "Age" : [25, 26, 28, 29, 30, 31], 
    "City": ["Dandeli", 'Hubli', "Delhi", "Mungowd", "Hubli", "Congo"]
}

df = pd.DataFrame(data)
df

          name  Age     City
0  Abdulrehman   25  Dandeli
1         Anup   26    Hubli
2      Kaushik   28    Delhi
3       Shivam   29  Mungowd
4        Vinay   30    Hubli
5       Ganesh   31    Congo

In [2]:
import pandas as pd
titanic_data = pd.read_csv("titanic.csv")
titanic_data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [7]:
titanic_data.loc[(titanic_data["Survived"]==1) & (titanic_data["Sex"]== "male"), ["PassengerId", "Name", "Sex", "Survived"]]

     PassengerId                             Name   Sex  Survived
17            18     Williams, Mr. Charles Eugene  male         1
21            22            Beesley, Mr. Lawrence  male         1
23            24     Sloper, Mr. William Thompson  male         1
36            37                 Mamee, Mr. Hanna  male         1
55            56                Woolner, Mr. Hugh  male         1
..           ...                              ...   ...       ...
838          839                  Chip, Mr. Chang  male         1
839          840             Marechal, Mr. Pierre  male         1
857          858           Daly, Mr. Peter Denis   male         1
869          870  Johnson, Master. Harold Theodor  male         1
889          890            Behr, Mr. Karl Howell  male         1

[109 rows x 4 columns]

In [11]:
older_passengers = titanic_data[titanic_data["Age"]>70]

In [16]:
titanic_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
females_survived = titanic_data.loc[(titanic_data["Sex"]=="female") & (titanic_data["Survived"]==1)]

In [20]:
males_survived = titanic_data.loc[(titanic_data["Sex"]=="male") & (titanic_data["Survived"]==1)].head(5)

In [22]:
females_survived.shape

(233, 12)

In [29]:
females_survived_name_age = titanic_data.loc[(titanic_data["Sex"]=="female") & (titanic_data["Survived"]==1), ["Name", "Age"]]

In [30]:
females_survived_name_age

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [28]:
females_survived.shape

(233, 12)

In [32]:
titanic_data.loc[0:4,["Name", "Age"]]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [33]:
titanic_data.iloc[0:5,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [34]:
titanic_data.loc[0:4,["Name", "Survived"]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4                           Allen, Mr. William Henry         0